---
engines:
  markdownlint:
    enabled: true
  fixme:
    enabled: false
  csslint:
    enabled: true
    checks:
      important:
        enabled: false
  eslint:
    enabled: true
ratings:
  paths:
    - "**.md"
    - "**.css"
    - "**.js"
exclude_paths:
  - docs/legacy
