version: "2"
services:
  build-docs:
    image: python:3
    command: ls -al && pip install -r requirements.txt
    working_dir: /usr/src/app
    volumes:
      -  $PWD:/usr/src/app

  server:
    image: python:3-onbuild
    command: 'pip install -r requirements.txt && mkdocs serve -a 0.0.0.0:8000'
    ports:
      - "8000:8000"
    volumes:
      -  $PWD:/usr/src/app

  test:
    image: 18fgsa/html-proofer
    command: site --allow-hash-href --check-html --empty-alt-ignore --disable-external
    volumes:
      -  $PWD/site:/site
