version: "2"
services:
  build-docs:
    build: .
    container_name: docs-build
    command: mkdocs build
    volumes:
      -  $PWD/site:/usr/src/app/site

  server:
    image: redbrick/docs
    container_name: docs-server
    ports:
      - "8000:8000"
    volumes:
      -  $PWD:/usr/src/app

  test:
    image: 18fgsa/html-proofer
    container_name: docs-test
    command: site
    volumes:
      -  $PWD/site:/site
