version: "2"
services:
  build-docs:
    image: python:3-onbuild
    container_name: docs-build
    command: mkdocs build
    volumes:
      -  $PWD:/usr/src/app

  server:
    image: python:3-onbuild
    container_name: docs-server
    command: 'mkdocs serve -a 0.0.0.0:8000'
    ports:
      - "8000:8000"
    volumes:
      -  $PWD:/usr/src/app

  test:
    image: 18fgsa/html-proofer
    container_name: docs-test
    command: site --allow-hash-href --check-html --empty-alt-ignore --disable-external
    volumes:
      -  $PWD/site:/site
