---
site_name: Redbrick Docs
theme:
  name: readthedocs
  hljs_languages:
    - yaml
    - bash
    - shell
    - xml
    - apache
    - python
    - ldif
    - Dockerfile
repo_url: https://github.com/redbrick/docs
strict: true
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/viz.js/1.7.1/viz.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  - js/github.js
  - js/graphviz.js
extra_css:
  - css/custom.css
nav:
  - Home: index.md
  - Plans:
      - Project Ideas: plans/project-ideas.md
  - Services:
      - Backuppc: services/backuppc.md
      - Bind9: services/bind9.md
      - Bitlbee: services/bitlbee.md
      - Git: services/git.md
      - Hackmd: services/hackmd.md
      - Hey: services/hey.md
      - IRC: services/irc.md
      - Icecast2: services/icecast2.md
      - LDAP: services/ldap.md
      - Mastodon: services/mastodon.md
      - MySQL: services/mysql.md
      - NFS: services/nfs.md
      - News: services/news.md
      - Pastebin: services/paste.md
      - Postgres: services/postgres.md
      - Tunnel.redbrick.dcu.ie: services/tunnel.redbrick.dcu.ie.md
      - Unified MOTD: services/unifiedmotd.md
  - Mail:
      - General: mail/index.md
      - Postfix: mail/postfix.md
      - Dovecot: mail/dovecot.md
      - Rspamd: mail/rspamd.md
      - Mailman: mail/mailman.md
      - Webmail: mail/webmail.md
  - Monitoring:
      - Grafana & Prometheus: monitoring/index.md
      - collectd: monitoring/collectd.md
      - tick: monitoring/tick.md
  - Procedures:
      - Abuse: procedures/abuse.md
      - Backporting Packages: procedures/backport-packages.md
      - Committee Changeover: procedures/committeechangeover.md
      - Docker Serivce: procedures/docker-service.md
      - DRAC Access: procedures/dracaccess.md
      - GPGKeys: procedures/gpgkeys.md
      - IRC Operations: procedures/irc_operator.md
      - LDAP chsh chfn: procedures/ldapchshchfn.md
      - Library Migration: procedures/library_migration.md
      - Mail Setup: procedures/mail_setup.md
      - Installing NixOS: procedures/nixos-install.md
      - New Installs: procedures/newinstalls.md
      - New board: procedures/newboard.md
      - New Domain: procedures/new_domain.md
      - News Overview Fix: procedures/newsoverviewfix.md
      - Passwd: procedures/passwd.md
      - Policies: procedures/policies.md
      - Post-Powercut: procedures/post_powercut.md
      - Pwsafe: procedures/pwsafe.md
      - RRS: procedures/rrs.md
      - Redbrick-apt: procedures/redbrick-apt.md
      - Severus Colocation: procedures/severuscolocation.md
      - Switch: procedures/switch.md
      - Ticketing: procedures/ticketing.md
      - Using NixOS: procedures/nixos.md
      - Upgrading Postgresql: procedures/postgres_upgrade.md
      - rb-ldap: procedures/rb-ldap.md
  - Hardware:
      - Daedalus and Icarus: hardware/daedalus_icarus.md
      - Albus: hardware/albus.md
      - Azazel: hardware/azazel.md
      - Halfpint: hardware/halfpint.md
      - Hardcase: hardware/hardcase.md
      - Metharme: hardware/metharme.md
      - PDUs: hardware/the_pdus.md
      - Paphos: hardware/paphos.md
      - Pygmalion: hardware/pygmalion.md
      - Zeus: hardware/zeus.md
      - IPKVM: hardware/ipkvm.md
  - Network:
      - Cisco iOS: network/ciscoios.md
      - Junos: network/junos.md
      - Network Setup: network/networksetup.md
  - Postmortems:
      - March 2016: postmortems/post_mortem_mar16.md
      - Template: postmortems/template.md
  - Web:
      - Apache: web/apache.md
      - SSL: web/ssl.md
      - Traefik: web/traefik.md
      - TechWeek: web/techweek.md
      - Webchat: web/webchat.md
      - Website: web/website.md
      - Webterm: web/term.md
  - Scripts:
      - Rbscripts: procedures/rbscripts.md
      - Rbusers: procedures/rbusers.md
  - Legacy: legacy/index.md
