---
site_name: Redbrick Docs
theme: readthedocs
repo_url: https://github.com/redbrick/docs
strict: true
markdown_extensions:
  - pymdownx.tasklist
extra_javascript:
  - js/github.js
  - js/viz-lite.js
  - js/graphviz.js
extra_css:
  - css/custom.css
nav:
  - Home: index.md
  - Plans:
      - Project Ideas: plans/project-ideas.md
      - TODO-2017: plans/TODO-2017.md
  - Services:
      - Backuppc: services/backuppc.md
      - Bind9: services/bind9.md
      - Bitlbee: services/bitlbee.md
      - Dovecot: services/dovecot.md
      - Exim: services/exim.md
      - Git: services/git.md
      - Hackmd: services/hackmd.md
      - Hey: services/hey.md
      - IRC: services/irc.md
      - Icecast2: services/icecast2.md
      - LDAP: services/ldap.md
      - Mailman: services/mailman.md
      - Mastodon: services/mastodon.md
      - MySQL: services/mysql.md
      - NFS: services/nfs.md
      - News: services/news.md
      - Pastebin: services/paste.md
      - Postgres: services/postgres.md
      - Tunnel.redbrick.dcu.ie: services/tunnel.redbrick.dcu.ie.md
      - Unified MOTD: services/unifiedmotd.md
  - Monitoring:
      - Grafana & Prometheus: monitoring/index.md
      - collectd: monitoring/collectd.md
      - tick: monitoring/tick.md
  - Procedures:
      - Abuse: procedures/abuse.md
      - Backporting Packages: procedures/backport-packages.md
      - Committee Changeover: procedures/committeechangeover.md
      - Docker Serivce: procedures/docker-service.md
      - DRAC Access: procedures/dracaccess.md
      - GPGKeys: procedures/gpgkeys.md
      - Gratuitous ARP: procedures/gratuitousarp.md
      - IRC Operations: procedures/irc_operator.md
      - LDAP chsh chfn: procedures/ldapchshchfn.md
      - Library Migration: procedures/library_migration.md
      - Mail Setup: procedures/mail_setup.md
      - New Installs: procedures/newinstalls.md
      - New board: procedures/newboard.md
      - News Overview Fix: procedures/newsoverviewfix.md
      - Passwd: procedures/passwd.md
      - Policies: procedures/policies.md
      - Post-Powercut: procedures/post_powercut.md
      - Pwsafe: procedures/pwsafe.md
      - RRS: procedures/rrs.md
      - Severus Colocation: procedures/severuscolocation.md
      - Switch: procedures/switch.md
      - Ticketing: procedures/ticketing.md
      - rb-ldap: procedures/rb-ldap.md
  - Hardware:
      - Daedalus and Icarus: hardware/daedalus_icarus.md
      - Albus: hardware/albus.md
      - Azazel: hardware/azazel.md
      - Halfpint: hardware/halfpint.md
      - Hardcase: hardware/hardcase.md
      - Metharme: hardware/metharme.md
      - PDUs: hardware/the_pdus.md
      - Paphos: hardware/paphos.md
      - Pygmalion: hardware/pygmalion.md
      - Zeus: hardware/zeus.md
      - IPKVM: hardware/ipkvm.md
  - Network:
      - Cisco iOS: network/ciscoios.md
      - Hadron: network/hadron.md
      - Higgs: network/higgs.md
      - Junos: network/junos.md
      - Main Address Space: network/mainaddressspace.md
      - Network Setup: network/networksetup.md
  - Postmortems:
      - March 2016: postmortems/post_mortem_mar16.md
      - Template: postmortems/template.md
  - Web:
      - Apache Modules: web/apachemodules.md
      - Apache: web/apache.md
      - PubCookie: web/pubcookie.md
      - SSL: web/ssl.md
      - SuPHP: web/suphp.md
      - Traefik: web/traefik.md
      - TechWeek: web/techweek.md
      - Webchat: web/webchat.md
      - Website: web/website.md
      - Webterm: web/term.md
  - Scripts:
      - Rbscripts: procedures/rbscripts.md
      - Rbusers: procedures/rbusers.md
  - Legacy: legacy/index.md
