---
version: 2.1
orbs:
  md-sheriff: nubank/md-sheriff@0.0.4
  eslint: arrai/eslint@1.3.0
jobs:
  "Lint Markdown": md-sheriff/run-lint
  build:
    docker:
      - image: 18fgsa/html-proofer
        environment:
          ENV: CI
    working_directory: ~/docs
    steps:
      - run: apk add --no-cache --virtual build-dependencies python3-dev git
      - checkout
      - run:
          name: Install Dependencies
          command: make circleci-dep
      - run:
          name: Test Build
          command: make build
      - run:
          name: Test Internal Links
          command: make test
