---
version: 2
jobs:
  build:
    docker:
      - image: python:3
        environment:
          ENV: CI
    working_directory: ~/docs
    steps:
      - checkout
      - run:
          name: Setup dep
          command: |
            set -x
            pip install -r requirements.txt
      - run:
          name: Test Build
          command: mkdocs build -v
      - setup_remote_docker
      - run:
          name: Test Internal Links
          command: |
            set -eo pipefail
            docker run -v /root/docs/site:/site 18fgsa/html-proofer /site | /results.txt
      - store_test_results:
          path: "/results.txt"
