---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    working_directory: /tmp/docs
    steps:
      - checkout
      - run: python3 -m pip install -r requirements.txt
      - run:
          name: Build site
          command: mkdocs build -v
      - persist_to_workspace:
          root: /tmp/docs
          paths:
            - site
  validate:
    docker:
      - image: circleci/ruby:2
    working_directory: /tmp/docs
    steps:
      - run: gem install html-proofer
      - attach_workspace:
          at: /tmp/docs
      - run:
          name: Test Internal Links
          command: |
            set -eo pipefail
            htmlproofer \
            --allow-hash-href \
            --check-html \
            --empty-alt-ignore \
            --disable-external \
            ./site
workflows:
  version: 2
  build_and_validate:
    jobs:
      - build
      - validate:
          requires:
            - build
