version: 2
jobs:
  build:
    docker:
      - image: golang:1.8.0
    working_directory: ~/docs
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Test Build
          command: docker-compose up build-docs
      - run:
          name: Test Internal Links
          command: |
            set -x
            docker-compose up test
