---
version: 2
jobs:
  build:
    docker:
      - image: 18fgsa/html-proofer
        environment:
          ENV: CI
    working_directory: ~/docs
    steps:
      - run: apk add --no-cache --virtual build-dependencies python3-dev git gcc musl-dev
      - checkout
      - run: python3 -m pip install -r requirements.txt
      - run:
          name: Test Build
          command: mkdocs build -v
      - run:
          name: Test Internal Links
          command: |
            set -eo pipefail
            htmlproofer \
            --allow-hash-href \
            --check-html \
            --empty-alt-ignore \
            --disable-external \
            ~/docs/site
      - store_test_results:
          path: "/results.txt"
