version: 2
jobs:
  build:
    docker:
      - image: golang:1.8.0
    working_directory: ~/docs
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run: ls -al bin
      - run:
          name: Test Build
          command: docker-compose run --rm build-docs
      - run:
          name: Test Internal Links
          command: |
            set -eo pipefail
            docker-compose run --rm test | tee /results.txt; exit ${PIPESTATUS[0]}
      - store_artifacts:
          path: /results.txt
          destination: reports
      - store_test_results:
          path: "/results.txt"
