# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and Validate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: Setup Ruby, JRuby and TruffleRuby
      uses: ruby/setup-ruby@v1.39.0
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        gem install html-proofer
    - name: Build site
      run: mkdocs build -v
    - name: Validate site's HTML
      run: |
        htmlproofer \
        --allow-hash-ref \
        --check-html \
        --empty-alt-ignore \
        --disable-external \
        ./site
