# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and Validate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run markdownlint (mdl)
      uses: bewuethr/mdl-action@v1.0.12
      with:
        style-file: .markdown.style.rb
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: Setup Ruby, JRuby and TruffleRuby
      uses: ruby/setup-ruby@v1.39.0
      with:
        ruby-version: ruby
    - name: Install dependencies
      run: |
        gem install html-proofer &
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        wait
    - name: Build site
      run: mkdocs build -s -v
    - name: Validate site's HTML
      run: |
        htmlproofer \
        --allow-hash-href \
        --check-html \
        --empty-alt-ignore \
        --disable-external \
        ./site
