name: Build and Validate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.52.0
      with:
        ruby-version: ruby
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        gem install html-proofer mdl &
        python -m pip install --upgrade pip setuptools
        python -m pip install wheel
        pip install -r requirements.txt
        wait
    - name: Run markdownlint (mdl)
      run: mdl -s .markdown.style.rb docs/
    - name: Build site
      run: mkdocs build -s -v
    - name: Validate site's HTML
      run: |
        htmlproofer \
        --allow-hash-href \
        --check-html \
        --empty-alt-ignore \
        --disable-external \
        ./site
